on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4'
      - name: Creating .env
        run: |
          touch .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          cat .env
      - name: Dependencies install
        run: flutter pub get
      - name: Build For Android
        run: flutter build apk --release --build-name 2.1.14 --build-number 5
      - name: Build For Windows
        run: flutter build windows --release --build-name 2.1.14 --build-number 5
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: Delta-2.1.14-windows.zip
          directory: build/windows/runner/Release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*,build/windows/runner/Release/Delta-2.1.14-windows.zip"
          tag: v2.1.14
          token: ${{ secrets.TOKEN }}
